### ISSUE TITLE
guild.join not working

### ISSUE THREAD

**Issue by otar120** [TreeBen77/DiscordOAuth2.py#3]
i made everything like you said but guild.join is not working. other functions are working.

**Comment by TreeBen77** [comment]
I can't help you if I can't see any code.

Some things to note:
1. `guild.join` requires a bot in that server with the `CREATE_INSTANT_INVITE` permission.
2. That bot must belong to the same OAuth2 application and it's bot token must be provided in your script.
3. (this is obvious) If you don't enable the `guild.join` scope during OAuth2, it can't add you to the server.
